/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jatoichi;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
    @Test void appHasVersion() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getApplicationVersion(), "app should have a version");
    }
}
