### help
GET http://localhost:21038/api/logs

### insert
POST http://localhost:21037/api/logs/insert
Content-Type: application/json

{
  "message": "test",
  "level": "info",
  "tags": [
    "test"
  ]
}

### list
POST http://localhost:21037/api/logs/list
Content-Type: application/json

{
 "page" : 1,
  "limit" : 10
}

### detail
POST http://localhost:21037/api/logs/detail
Content-Type: application/json

{
  "id": "67050c21aaab604d05e69d08"
}


### delete
POST http://localhost:21037/api/logs/delete
Content-Type: application/json

{
  "_id": "6450d61f9a2470789cc44403"
}


### update
POST http://localhost:21037/api/logs/update
Content-Type: application/json

{
  "id": "67136f184d4d7e4e6371a943",
    "update": {
        "message": "message update",
        "title": "title update1",
        "content": "content update"
    }
}