wifi.setmode(wifi.STATIONAP)
srv=net.createServer(net.TCP)
testdata = "{}"
srv:listen(1471,function(conn)
    print("new connect")
    conn:on("receive",function(conn,payload)
        --_, _, method, path, vars = string.find(payload, "([A-Z]+) /([^?]*)%??(.*) HTTP");print(path)
        conn:send(testdata,function() conn:close() print(node.heap())  end)
        print(node.heap())
        conn:close()
    end)
end)
