/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jatoichi;


import javax.swing.SwingUtilities;
import com.fazecast.jSerialComm.SerialPort;

public class App {

    public String applicationName = "jatoich";
    private SerialPort serialPort;

    public App() {
        // 생성자
    }

    public static void main(String[] args) throws Exception {
        
        // System.out.println("Hello, World!");

        // System.out.println("jatoichi " + new App().getApplicationVersion());

        // App 객체 생성
        App app = new App();

        System.out.println("jatoichi " + app.getApplicationVersion());

        // Event Dispatch Thread에서 GUI 초기화
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainFrame frame = new MainFrame(app);
                frame.setVisible(true);
            }
        });
    }

    public synchronized void setSerialPort(SerialPort port) {
        this.serialPort = port;
    }

    public synchronized SerialPort getSerialPort() {
        return serialPort;
    }
    
    public String getApplicationVersion() {
        return "0.0.1";
    }

    
}
